language: php

php:
  - 7.2

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist
  - composer require codeclimate/php-test-reporter

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 - ./vendor/bin/test-reporter --coverage-report build/logs/clover.xml